import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, { useState, useEffect } from 'react';
import {
  Collapse,
  Navbar,
  NavbarToggler,
  NavbarBrand,
  Nav,
  NavItem,
  NavLink,
  UncontrolledDropdown,
  DropdownToggle,
  DropdownMenu,
  UncontrolledCarousel,
  NavbarText,
  Input,
  InputGroup,
  InputGroupText,
  Row,
  Col, Card, CardTitle, CardText, Button, Container, CardBody, CardSubtitle
} from 'reactstrap';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Search } from 'iconoir-react';
const Axios = require('@/helper/axios')

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  Axios.get('/v1/api/product').then((result) => {
    console.log(result.data)
  }).catch((err) => {
    console.log(err.message)
  });
  // console.log('DATA::::::::::', response)
  return {
    props: {
      
    },
  };
}

export default  function Home({ APIKEY }) {
  const [isOpen, setIsOpen] = useState(false);
  const toggle = () => setIsOpen(!isOpen);



  return (
    <>
      <Head>
        <title>Shoppuu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar
          fixed="top"
          container="sm"
          expand={true}
          className=""
        >
          <NavbarBrand href="/">Shoppuu</NavbarBrand>
          <NavbarToggler onClick={toggle} />
          <Collapse isOpen={isOpen} navbar>
            <Nav className="me-auto" navbar>
              <NavItem>
                <Link href={"/login/shop"} className="nav-link">
                  Kênh người bán
                </Link>
              </NavItem>
              <NavItem>
                <InputGroup>
                  <Input placeholder="Tìm sản phẩm ..." />
                  <InputGroupText>
                    <Search />
                  </InputGroupText>
                </InputGroup>
              </NavItem>
            </Nav>
            <NavbarText>
              <Link href={"/login/user"} className="nav-link">
                Đăng Nhập
              </Link>
            </NavbarText>
          </Collapse>
        </Navbar>
      </div>
      <UncontrolledCarousel
        style={{ marginTop: 55 }}
        slide={true}
        fade={true}
        items={[
          {
            altText: "Slide 2",
            caption: "Slide 2",
            key: 2,
            src: "/images/shopee-2.jpg",
          }
        ]}
      />
      <main className={`${styles.main} ${inter.className}`}>
        <Container>
          <Card className="p-2">
            <CardTitle tag="h5">Danh mục</CardTitle>
            <Row>
              <Col md={3}>
                <Card body>
                  <CardTitle tag="h6">Thời trang</CardTitle>
                  <CardText>
                    With supporting text below as a natural lead-in to
                    additional content.
                  </CardText>
                </Card>
              </Col>
            </Row>
          </Card>
        </Container>

        <Container>
          <h4>Sản phẩm</h4>
          <Row>
            <Card
              style={{
                paddingTop: 5,
                margin: 3,
                width: "15rem",
              }}
            >
              <img alt="Sample" src="https://picsum.photos/300/200" />
              <CardBody>
                <CardTitle tag="h5">Card title</CardTitle>
                <CardSubtitle className="mb-2 text-muted" tag="h6">
                  Card subtitle
                </CardSubtitle>
                <CardText>
                  Some quick example text to build on the card title and make up
                  the bulk of the card‘s content.
                </CardText>
              </CardBody>
            </Card>
            <Card
              style={{
                paddingTop: 5,
                margin: 3,
                width: "15rem",
              }}
            >
              <img alt="Sample" src="https://picsum.photos/300/200" />
              <CardBody>
                <CardTitle tag="h5">Card title</CardTitle>
                <CardSubtitle className="mb-2 text-muted" tag="h6">
                  Card subtitle
                </CardSubtitle>
                <CardText>
                  Some quick example text to build on the card title and make up
                  the bulk of the card‘s content.
                </CardText>
              </CardBody>
            </Card>
            <Card
              style={{
                paddingTop: 5,
                margin: 3,
                width: "15rem",
              }}
            >
              <img alt="Sample" src="https://picsum.photos/300/200" />
              <CardBody>
                <CardTitle tag="h5">Card title</CardTitle>
                <CardSubtitle className="mb-2 text-muted" tag="h6">
                  Card subtitle
                </CardSubtitle>
                <CardText>
                  Some quick example text to build on the card title and make up
                  the bulk of the card‘s content.
                </CardText>
              </CardBody>
            </Card>
            <Card
              style={{
                paddingTop: 5,
                margin: 3,
                width: "15rem",
              }}
            >
              <img alt="Sample" src="https://picsum.photos/300/200" />
              <CardBody>
                <CardTitle tag="h5">Card title</CardTitle>
                <CardSubtitle className="mb-2 text-muted" tag="h6">
                  Card subtitle
                </CardSubtitle>
                <CardText>
                  Some quick example text to build on the card title and make up
                  the bulk of the card‘s content.
                </CardText>
              </CardBody>
            </Card>
          </Row>
        </Container>

        <div className={styles.grid}></div>
      </main>
    </>
  );
}
