import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/shop.module.css'
import React, { useState, useEffect } from 'react';
import { Search } from 'iconoir-react';
const Axios = require('@/helper/axios')

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {

  return {
    props: {
      
    },
  };
}

export default  function Home({ APIKEY }) {

  return (
    <>
      <Head>
        <title>Shoppuu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Naviagtion */}
      <div className="nav">
        <ul className="nav-list">
          <li className="nav-item">Giới thiệu</li>
          <li className="nav-item">Kết nối</li>
        </ul>
        <ul className="nav-list">
          <li className="nav-item">Giới thiệu</li>
          <li className="nav-item">Kết nối</li>
        </ul>
      </div>

      {/* Input Box */}
      <div className="form-container">
        <div className="form">
          <div className="form__row">
            <label className="form__label" for="name">
              Name:{" "}
            </label>
            <input className="form__input" type="text" id="name"></input>
          </div>
          <div className="form__row">
            <label className="form__label" for="password">
              Password:{" "}
            </label>
            <input className="form__input" type="text" id="password"></input>
          </div>
        </div>
      </div>

      {/* Column layout */}
      <div className="column-layout">
        <div className="column-item sidebar-one">
          <h1>Sidebar One</h1>
          <p>Write shomething here</p>
        </div>
        <div className="column-item sidebar-main">
          <h1>Sidebar One</h1>
          <p>Write shomething here</p>
        </div>
        <div className="column-item sidebar-two">
          <h1>Sidebar One</h1>
          <p>Write shomething here</p>
        </div>
      </div>

      {/* Feature layout */}
      <div className="feature-layout">
        <div className="feature-item">
          <h1>Feature 1</h1>
          <p>Write shomething here</p>
        </div>
        <div className="feature-item">
          <h1>Feature 2</h1>
          <p>Write shomething here</p>
        </div>
        <div className="feature-item">
          <h1>Feature 3</h1>
          <p>Write shomething here</p>
        </div>
      </div>

      {/* Wrap layout */}
      <div className="wrap-layout">
        <div className="warp-layout__item">1</div>
        <div className="warp-layout__item">2</div>
        <div className="warp-layout__item">3</div>
        <div className="warp-layout__item">4</div>
        <div className="warp-layout__item">5</div>
      </div>

      {/* Center layout */}
      <div className="center-layout">
        <p className="center-layout__item">Center layout</p>
      </div>

      {/* Chart Layout */}
      <div className="chart-layout">
        <div className="chart-layout__item" style={{ height: "60%" }}>
          60
        </div>
        <div className="chart-layout__item" style={{ height: "80%" }}>
          80
        </div>
        <div className="chart-layout__item" style={{ height: "10%" }}>
          10
        </div>
        <div className="chart-layout__item" style={{ height: "30%" }}>
          30
        </div>
        <div className="chart-layout__item" style={{ height: "40%" }}>
          40
        </div>
        <div className="chart-layout__item" style={{ height: "10%" }}>
          10
        </div>
        <div className="chart-layout__item" style={{ height: "30%" }}>
          30
        </div>
        <div className="chart-layout__item" style={{ height: "60%" }}>
          60
        </div>
        <div className="chart-layout__item" style={{ height: "80%" }}>
          80
        </div>
        <div className="chart-layout__item" style={{ height: "10%" }}>
          10
        </div>
        <div className="chart-layout__item" style={{ height: "30%" }}>
          30
        </div>
        <div className="chart-layout__item" style={{ height: "40%" }}>
          40
        </div>
      </div>

      {/* The End */}
      <div className="the-end">
        <div className="the-end__first">
          <p>Writing something!!</p>
          <p>Hello!!! How are you to day.</p>
        </div>
        <div className="the-end__second">
          <div className="the-end__second-one">
            <p>Writing something!!</p>
          </div>
          <div className="the-end__second-two">
            <p>Writing something!!</p>
          </div>
        </div>
      </div>

      <main className={`${styles.main} ${inter.className}`}></main>
    </>
  );
}
