@url_api_dev = http://localhost:3000/v1/api

### Sign up
POST {{url_api_dev}}/shop/signup
Content-Type: application/json
x-api-key: 86d0aae728d5e75ad59dcc6ab3f29eb49b220980dd888ef3a8c2d17c0a27f2c23d73c4313882f33c49489f52105dd039268884829a7225cddf3d00ec44719838

{
    "name": "Shop dev 1",
    "email": "huy.nguyen2994@gmail.com",
    "password": "1234567"
}

### LogIn
POST {{url_api_dev}}/shop/login
Content-Type: application/json
x-api-key: 86d0aae728d5e75ad59dcc6ab3f29eb49b220980dd888ef3a8c2d17c0a27f2c23d73c4313882f33c49489f52105dd039268884829a7225cddf3d00ec44719838

{
    "email": "huy.nguyen2994@gmail.com",
    "password": "1234567"
}

### LogOut
POST {{url_api_dev}}/shop/logout
Content-Type: application/json
x-api-key: 86d0aae728d5e75ad59dcc6ab3f29eb49b220980dd888ef3a8c2d17c0a27f2c23d73c4313882f33c49489f52105dd039268884829a7225cddf3d00ec44719838
x-client-id: 64df37b951ebeaae2ba427de
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGRmMzdiOTUxZWJlYWFlMmJhNDI3ZGUiLCJlbWFpbCI6Imh1eS5uZ3V5ZW4yOTk0QGdtYWlsLmNvbSIsImlhdCI6MTY5MjM2MDQyMiwiZXhwIjoxNjkyOTY1MjIyfQ.EoQr8mJrB6nChWlqIBHE9eRdd5NgzVN7M9qZCESc933-IX1bDh-rNC1AlE8mB54YO7HkulSPXlIwO5CUklO3XQ3-iSTui2xK4zZxQQdgJ841Runn-v4iQ0xBkOBQRtxaN6RekaovTWEx1cBsFijQehcEDy_sUJvgRI2eDjNeKTT2Ta4bbnZIfKOl9rU13fOqwX32xvTY8271cME-hkAA06qyuTgwntEcunNdWfuPBv5uv6r16vv1Ph2AbI55eBr9K-EyLvOxnXD-l5GAk6FoHSMQTWP7phH5ZYncC71XF-m3Nofea4zLmvakb2-76CvQNGyCQaeIEYxBvUV4wPEWG3-M8KsFuvUqv8IUeBjcpLDsZJNZZwLKRmI14GAFOLqmnyxhZmIIybABuV5-Oj0bHnmq_Y15F2xdrbdSPG6O6nQsvjbtVdVMRC8H6a1pSj80BjPXjVwDIKV517k77QwkhuzDQo0A2033WVL__1XcAH9wtxrETn46S3_ZxVchsilLV5QHG2PyRE-UwEC8humpQN-YdbYnIJw8jKqRo-Co0JShoiFZCuSglhOC5STmYO5eO4iTIejFOAHWrLFgacbvDTaOtRp0-bhOLAbWeIFG9PqxuXbDZZDMwqDjpqIRKDXkLNmI5H7GEFjO1cIYWWUGXzmE1dc8fsODEzofz9JNPAM