@url_api_dev = http://localhost:3000/v1/api

### Create new cart from user
POST {{url_api_dev}}/checkout/review
Content-Type: application/json
x-api-key: 1837ffa7e5bc0c6aa5ccf91462729d7102bdcafd7864541bf04b997e7eba342b066dbfa0462c8e1a6ed9e8ec7b5b622f025f07f7b71d61d416fd9cfc34a4dc51

{
    "userId": 1001,
    "cartId": "64ef778723ce391c12400666",
    "shop_order_ids": [
        {
            "shopId": "64ee1ecb8979971154cfe17a",
            "shopDiscount": [
                {
                    "shopId": "64ee1ecb8979971154cfe17a",
                    "discountId": "64ee2287584a07a7853932e8",
                    "codeId": "SHOP-1234"
                }
            ],
            "item_products": [
                {
                    "quantity": 1,
                    "productId": "64ee21b781ac1055c94ae724"
                }
            ]
        },
        {
            "shopId": "64f14935b41b4e8c9eeeb3b8",
            "shopDiscount": [
                {
                    "shopId": "64f14935b41b4e8c9eeeb3b8",
                    "discountId": "64f14a3fb41b4e8c9eeeb3c6",
                    "codeId": "SHOP-2-1234"
                },
                {
                    "shopId": "64f14935b41b4e8c9eeeb3b8",
                    "discountId": "64f14aafb41b4e8c9eeeb3cb",
                    "codeId": "SHOP-percent-1234"
                }
            ],
            "item_products": [
                {
                    "quantity": 1,
                    "productId": "64f14998b41b4e8c9eeeb3bd"
                }
            ]
        }
    ]
}