@url_api_dev = http://localhost:3000/v1/api

### Create comment Shop
POST {{url_api_dev}}/comment
Content-Type: application/json
x-api-key: 1837ffa7e5bc0c6aa5ccf91462729d7102bdcafd7864541bf04b997e7eba342b066dbfa0462c8e1a6ed9e8ec7b5b622f025f07f7b71d61d416fd9cfc34a4dc51
x-client-id: 64ee1ecb8979971154cfe17a
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVlMWVjYjg5Nzk5NzExNTRjZmUxN2EiLCJlbWFpbCI6Imh1eS5uZ3V5ZW4yOTk0QGdtYWlsLmNvbSIsImlhdCI6MTY5NDU4NzAwNiwiZXhwIjoxNjk0NzU5ODA2fQ.GIcbJtUo6EVQhqRPL-UEQhx9bE08fPEG-ewreGjr1GSMpR2VCnwbUQwoFpKtczlqmvARsZq8Wx8pIMTz_ijBX3ewkn8a7WbZNhDGdmZVg7VqubPwtqsIWqvrooT7l1QuTDc5sWEtcPKDO0EpVbw4Ki8y75kEwETvCHZq2tMFrWby1rTQc0PQ9mTCJqbJQcWxL7lJkWNRTa6Zx2gzqEyGhP2qdkbt2DV50xQNGgj6BsKYm4nCa8qxC2lwdJq1U0duvTg9Um8GDfriT1IJ-Fdhh2LVGT8A32Ryz7h6YuJf6qRXCEygi7wZ2zMlk-_xR85OIaF5cD6VFJ-NRglalx_b1ZrJt-1y7X__D-w4dUa-N2QlHQ5aBNdFP56ie886m43rYEeFNnworTbM7_dGQ0dUekEnFdITpyWbJo9P42ufH8dX4xY3DLjS3XHOTHcHNZPpsEUoGoParnGK5EPwsMDH1SsjStkvnTvJ_qkXzzabxrB9l5Wxa56rE6rAQvQ7YwCQPzzW-rE1VcmPtBEHXDVLgHwzmzYIxyxj7E2HCIoWJ7mUcOxJ-7qFVvW-i_e0q6PABbl6XZxHEUeBQAtOmF_K35gbEKww_hTdtxZwTPPg2nXS1vZF7IKnhiS5B9GMBoOoAYNKIntLfdnb_Ny5IzG3MSVu0mYSUS99XE88jeiQ0Ag

{
    "productId": "64ee21b781ac1055c94ae724", 
    "userId": 1001, 
    "content": "Comment 1.2.2", 
    "parentCommentId": "6502ae661a69e5d4a889433f"
}

### Get Comment Shop
GET {{url_api_dev}}/comment?productId=64ee21b781ac1055c94ae724&parentCommentId=6502ae661a69e5d4a889433f
Content-Type: application/json
x-api-key: 1837ffa7e5bc0c6aa5ccf91462729d7102bdcafd7864541bf04b997e7eba342b066dbfa0462c8e1a6ed9e8ec7b5b622f025f07f7b71d61d416fd9cfc34a4dc51
x-client-id: 64ee1ecb8979971154cfe17a
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVlMWVjYjg5Nzk5NzExNTRjZmUxN2EiLCJlbWFpbCI6Imh1eS5uZ3V5ZW4yOTk0QGdtYWlsLmNvbSIsImlhdCI6MTY5NDU4NzAwNiwiZXhwIjoxNjk0NzU5ODA2fQ.GIcbJtUo6EVQhqRPL-UEQhx9bE08fPEG-ewreGjr1GSMpR2VCnwbUQwoFpKtczlqmvARsZq8Wx8pIMTz_ijBX3ewkn8a7WbZNhDGdmZVg7VqubPwtqsIWqvrooT7l1QuTDc5sWEtcPKDO0EpVbw4Ki8y75kEwETvCHZq2tMFrWby1rTQc0PQ9mTCJqbJQcWxL7lJkWNRTa6Zx2gzqEyGhP2qdkbt2DV50xQNGgj6BsKYm4nCa8qxC2lwdJq1U0duvTg9Um8GDfriT1IJ-Fdhh2LVGT8A32Ryz7h6YuJf6qRXCEygi7wZ2zMlk-_xR85OIaF5cD6VFJ-NRglalx_b1ZrJt-1y7X__D-w4dUa-N2QlHQ5aBNdFP56ie886m43rYEeFNnworTbM7_dGQ0dUekEnFdITpyWbJo9P42ufH8dX4xY3DLjS3XHOTHcHNZPpsEUoGoParnGK5EPwsMDH1SsjStkvnTvJ_qkXzzabxrB9l5Wxa56rE6rAQvQ7YwCQPzzW-rE1VcmPtBEHXDVLgHwzmzYIxyxj7E2HCIoWJ7mUcOxJ-7qFVvW-i_e0q6PABbl6XZxHEUeBQAtOmF_K35gbEKww_hTdtxZwTPPg2nXS1vZF7IKnhiS5B9GMBoOoAYNKIntLfdnb_Ny5IzG3MSVu0mYSUS99XE88jeiQ0Ag
