@url_api_dev = http://localhost:8000/v1/api

### Get List Notification By User
GET {{url_api_dev}}/notification
Content-Type: application/json
x-api-key: 1837ffa7e5bc0c6aa5ccf91462729d7102bdcafd7864541bf04b997e7eba342b066dbfa0462c8e1a6ed9e8ec7b5b622f025f07f7b71d61d416fd9cfc34a4dc51
x-client-id: 64ee1ecb8979971154cfe17a
authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGVlMWVjYjg5Nzk5NzExNTRjZmUxN2EiLCJlbWFpbCI6Imh1eS5uZ3V5ZW4yOTk0QGdtYWlsLmNvbSIsImlhdCI6MTY5NTAwNzc1MCwiZXhwIjoxNjk1MTgwNTUwfQ.ZgI6PzFQmzgS4u525d7VPidt8NKAa1HIUquTxlCO1d3pUpRADIPjbln7p6cmJ0onND9w7L-wlwWj-KcVVsRlNK8mMTqepH6GQnYYkEgYkv9RWlgjM0GYTBBV0Ua7dTps3NXpQnBm2Y6YBWRiTmLLZxQeUL53pBMMw0y5tyibsXH6cH0qFlHyM7FxXkZJHqGyBLreyGxer3o4NzRc2L0CZlJgJ5sLHDKktBHbw2JAGadaKVHEk0P8uIxTFEM9nG9XsXIDB8eKb515hOI2apdNwLQ4z6YvGn_IS67fh7KRtP-qx7wefZt_ezcyVIhQfOSDekx4069kZT6UVfP43U-1eOMdu2OmOmjYvQvbU7iqjxdg8mrBibkG59cnC1IUfCzbFjnRamQZTPrxCOKYncOzkqdeRpHz8GudVHsaU2zJ39lqbKmnMtcz3F4n5uyd335EqmPffj9ZF1bCF1Ln3Z-KiX4y-w3f9dy6w6UE001QuhlnYoK6ABuA5bbnoyJTk7gqbPBGieNDA1NoC57_z2WUm3fAWF_g29q_jQK1txtZoYOr6EpQmAaB8S2LVaC6oAQKoglGaUonAHQY5UJITEAIWTw_athSkDP_eeQypPkGCZKQSfF4Ohex0sZvdBK4EJNysNGu2018U5L0_GwYYyZQ3_dbtIkos8deG_qtgUDRqUg